name = "Game Hyde"
license = "MIT"
licenselink = "https://github.com/claydowling/game-hyde/blob/master/LICENSE.md"
description = "An elegant open source and mobile first theme"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.53

[author]
    name = "Clay Dowling"
    homepage = "http://claydowling.com"

# If Porting existing theme
[original]
    author =  "mdo"
    homepage = "http://markdotto.com/"
    repo = "https://www.github.com/mdo/hyde"
